from backend.app.connectors.two_stage_crawler import TwoStageJobIngestionPipeline

# Alias for backward compatibility in registry
TechCareersConnector = TwoStageJobIngestionPipeline
LiveCompanyCareersConnector = TwoStageJobIngestionPipeline
